os: linux
arch: arm64
dist: xenial

env:
  matrix:
    - CI_NODE_INDEX=0

script:
  - echo TEST
  - echo $TRAVIS_CPU_ARCH
  - uname -a
  - curl http://169.254.169.254/latest/meta-data/instance-type
  - echo $(curl http://169.254.169.254/latest/meta-data/instance-type)
  
